### ISSUE TITLE
ggplot.multistats instead of geom_hex?

### ISSUE THREAD

**Issue by flying-sheep** [SaskiaFreytag/schex#13]
Hi, I recently published [ggplot.multistats](https://github.com/flying-sheep/ggplot.multistats#readme) on CRAN. You might be interested!

**Comment by SaskiaFreytag** [comment]
This is a great suggestion. Would you mind notify me when it is on CRAN, as only then can it be part of the package.

**Comment by flying-sheep** [comment]
uh 14 or so days ago!
