### ISSUE TITLE
devel_conference install errors

### ISSUE THREAD

**Issue by drneavin** [SaskiaFreytag/schex#16]
Hi Saskia,

I am trying to install the developmental version of schex because I am interested in using the plot_hexbin_bivariate function. However, I have had some issues installing the devel_conference version. The first issue I ran across is a missing parenthesis in the plot_hexbin_bivariate code at line 150 which throws the following error when I try to install using install_github():
```Error in parse(outFile) : 
  /tmp/RtmpRFHm24/R.INSTALLb94b557299e/schex/R/plot_hexbin_bivariate.R:151:3: unexpected '}'
150:     "8-4", "#b7cac9")
151:   }
```

So I cloned the devel_conference branch directly, fixed the missing parethesis and tried to directly build it in R. However, I receive the following error:
```Error in grid.newpage() : could not find function "grid.newpage" ```
even though I have grid attached and can use the grid.newpage function.

Would you please advise on how I might be able to install the devel_conference branch of schex?

Thanks for your help!

-Drew

**Comment by SaskiaFreytag** [comment]
Hi Drew,

Thanks for your interest in the package. Unfortunately, the development version is still under development. I will get to it in the next week and finish it up. I just deposited the scripts there, so I could have access during the holidays.

Cheers,

Saskia

**Comment by SaskiaFreytag** [comment]
Hi Drew,

Thanks for your interest in the package. Unfortunately, the development version is still under development. I will get to it in the next week and finish it up. I just deposited the scripts there, so I could have access during the holidays.

Cheers,

Saskia

**Comment by drneavin** [comment]
Hi Saskia,

Yes, I thought that might be the case but I thought I would check anyway. We are very keen to try out your new functions and will be keeping an eye out for their release. Thanks for your help!

Cheers,
Drew

**Comment by SaskiaFreytag** [comment]
Hi Drew,

The bivariate plot features are now integrated. Hope this works for you.

Cheers,

Saskia
