### ISSUE TITLE
Display fraction of cells from a given annotation

### ISSUE THREAD

**Issue by vertesy** [SaskiaFreytag/schex#18]
Hey Saskia,

I am looking for a way to visualize the fraction of cells from a given annotation (e.g. 'dataset of origin', stored in the Seurat metadata of an integrated dataset, A+B=100%).

Is their a way I can use `schex` to do that? (Or do you know of another good way to do this?)

Thanks,
Abel

**Comment by SaskiaFreytag** [comment]
Hi Abel,

This is already implemented. Have a look at the `plot_hexbin_meta(sce, col="Dataset_of_origin", action="prop", no=1)`. Just make sure that the column names do not have spaces. Let me know if you have any further issues.

Cheers,

Saskia

**Comment by vertesy** [comment]
Thanks Saskia, thats great, will take a look!

Cheers,
Abel

On 22.02.2020, at 05:37, Saskia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Abel,

This is already implemented. Have a look at the plot_hexbin_meta(sce, col="Dataset_of_origin", action="prop", no=1). Just make sure that the column names do not have spaces. Let me know if you have any further issues.

Cheers,

Saskia

**Comment by SaskiaFreytag** [comment]
I will close this now, as I think it has been addressed.
