### ISSUE TITLE
spaces in gene names causing parsing error with plot_hexbin_feature

### ISSUE THREAD

**Issue by muss0044** [SaskiaFreytag/schex#19]
I'm running into this error with plot_hexbin_feature when running it on a seurat object:

Error in parse(text = func1) : <text>:1:19: unexpected symbol
1: out$comp121417_c0 RAB27A

I have spaces in my gene names which seem to be causing the problem. I can convert all of my spaces to periods for instance, although it would be nice to accommodate spaces if possible.

**Comment by SaskiaFreytag** [comment]
Yep that is a super fair point. I will have a look at that.

**Comment by SaskiaFreytag** [comment]
Should be fixed now.
