### ISSUE TITLE
Error in tapply on plot_hexbin_meta

### ISSUE THREAD

**Issue by vertesy** [SaskiaFreytag/schex#20]
Hi Saskia, thanks for the great package!

I unfortunately get an error in `plot_hexbin_meta` when using `umap`, but not `tsne` or `pca`. I can plot features on umap, so the problem is not simply with `umap` missing.

#### Works well:
```r
combined.obj <- make_hexbin(sce = combined.obj, nbins = 25, dimension_reduction = "tsne")
plot_hexbin_meta(sce = combined.obj, col = "percent.mito", action = "mean" )
```

#### Breaks:
```r
combined.obj <- make_hexbin(sce = combined.obj, nbins = 25, dimension_reduction = "umap")
plot_hexbin_meta(sce = combined.obj, col = "percent.mito", action = "mean" )

> Error in tapply(x, cID, FUN = function(z) mean(z, na.rm = na.rm)) : 
  arguments must have same length
```

I used it with umap before on other data, so I guess something is unusual about the object.
(E.g.: The object has been previously subset.)

Do you have suggestion? Thanks!

**Comment by vertesy** [comment]
It actually has to do with `subset`.

-  After I subset the Seurat object, the UMAP coordinates were not subset.
- `Dimplot` & co probably pull by cell name, so it works fine.
- I guess, `plot_hexbin_meta`  does not do that, so it fails downstream

**Comment by SaskiaFreytag** [comment]
Thank you for reporting this issue. I will make a fix in the next couple of days.

**Comment by SaskiaFreytag** [comment]
Actually I cannot reproduce your error (I tried subsetting the example dataset `pbmc_small` in Seurat and then follow your instructions. It worked just fine.) . What version of schex are you using?

**Comment by vertesy** [comment]
Thanks Saskia! 
It goes a bit deeper (3D umap coord's stored in @misc throughout subsetting), and the error only happens if your @umap does not match `colnames(obj)`. It's just a simple check to account for this when drawing hex. You can as well label the issue as `close` it should not normally happen - something I figured out  throughout this thread :-)
