### ISSUE TITLE
Feature request: user specified color

### ISSUE THREAD

**Issue by davemcg** [SaskiaFreytag/schex#5]
Viridis is always my first choice, but sometimes I have other needs....tried digging a bit into the code and can't figure out where you are specifying the color scheme.

**Comment by SaskiaFreytag** [comment]
I think I can change that, but I am gonna need a bit of time. Probably get back to you with a solution tomorrow.

**Comment by SaskiaFreytag** [comment]
Good news I don't actually have to change anything for this to work. You can simply rely on the old ggplot2 syntax in order to change the colour. It produces a warning message but that can be safely ignored. Here is an example:

```
library(Seurat)
data("pbmc_small")
pbmc_small <- make_hexbin(pbmc_small, 10, dimension_reduction = "PCA")
plot_hexbin_density(pbmc_small)
plot_hexbin_density(pbmc_small) + scale_fill_continuous()
```

**Comment by davemcg** [comment]
Perfect thanks! 

For anyone who wants a Seurat-like gray to something scheme, just add:

` + scale_fille_gradient(low = 'gray', high = 'blue')`
